export const spendingCategories = [
    "ABONAMENTE",
    "ASIGURARI",
    "BAUTURI",
    "BUNURI_DE_LUX",
    "COSMETICE",
    "DIVERTISMENT",
    "EDUCATIE",
    "HOBBY_URI",
    "INVESTITII",
    "LOCUINTA",
    "MANCARE",
    "SANATATE",
    "TAXE",
    "TEHNOLOGIE",
    "TRANSPORT",
    "UZ_CASNIC",
    "IMBRACAMINTE"
];
